dist: trusty
sudo: required 

language: cpp
cache: ccache
  
install:
  - sudo apt update
  - sudo apt install mpi-default-bin mpi-default-dev
  - export PATH="$HOME/opt/bin:$PATH"
  - export LD_LIBRARY_PATH="$HOME/opt/lib:$LD_LIBRARY_PATH"
  - sudo ln -s ccache /usr/local/bin/mpic++
  - export PATH=/usr/lib/ccache:${PATH}
  - ccache -s
# version=master or version=f123f12f3 to select a specific version
  - CXX="mpic++" .travis/install.plumed
# patch=lammps-6Apr13 to select a patch
# patch=no to skip patching
# repo=https://github.com/gtribello/lammps.git to clone a given repository (rather than official lammps)
# version=pablo-fix to checkout a specific version
  - .travis/install.lammps patch=lammps-6Apr13
  - ccache -s

script:
  - ./run-tests.sh
# should add something that makes the script fail when there are errors
